/**
 * AUTO-GENERIERT von scripts/build-default-labels.mjs aus _labels/*.xlsx
 * NICHT MANUELL EDITIEREN — bei Aenderungen XLSX anpassen + npm run build:default-labels
 *
 * Quelle: _labels/Labels PrjBsp_GPT.xlsx (4-Zeilen-Header)
 *  - Zeile 2 = Klartext, Zeile 3 = CSV-Spalten-Code  -> LABEL_BY_CSV_COLUMN
 *  - Zeile 1 = ZT-Themenfeld-Name (Sub-Gruppe)       -> ZUKUNFTSTECHNOLOGIE_FELDER
 */

export type UeberkategorieId = 'IT' | 'DT' | 'EU' | 'LG' | 'NM';

/** Klarnamen pro CSV-Spalten-Code (aus Labels-XLSX). */
export const LABEL_BY_CSV_COLUMN: Record<string, string> = {
  "01 - Innov": "Innovationstag VB-Ebene",
  "02 - Hanno": "Hannover Messe VB-Ebene",
  "03 - Erfol": "Erfolgsbeispiel VB-Ebene",
  "05 - anspr": "anspruchsvolles Projekt eines Start-Up-Unternehmens (FuE) TV-Ebene",
  "05 - Biote": "Biotechnika VB-Ebene",
  "05 - Netzw": "Netzwerk mit Beteiligung eines Start-Up-Unternehmens (NW) VB-Ebene",
  "06 - anspr": "anspruchsvolles Projekt eines Handwerksbetriebes (FuE) TV-Ebene",
  "06 - Netzw": "Netzwerk mit Beteiligung von Handwerksbetrieben (NW) VB-Ebene",
  "06 - weite": "weitere Fachmesse VB-Ebene",
  "07 - ZIM-P": "ZIM-Preis VB-Ebene",
  "08 - FachP": "FachPack VB-Ebene",
  "09 - FormN": "FormNext VB-Ebene",
  "09 - Proje": "Projektinhalt mit sehr guter Öffentlichkeitswirkung (FuE) VB-Ebene",
  "09-ProjeNW": "Projektinhalt mit sehr guter Öffentlichkeitswirkung (NW) VB-Ebene",
  "10 - beson": "besonders repräsentativer Geschäftsführer/Netzwerkmanager (Referent?) (NW) VB-Ebene",
  "10 - Green": "GreenTech VB-Ebene",
  "11 - Handw": "Handwerksmesse VB-Ebene",
  "28 - Betei": "Beteiligung eines Handwerksunternehmens (FuE) VB-Ebene",
  "Additive F": "Additive Fertigung / 3D-Druck TV-Ebene",
  "Additive F23": "Additive Fertigung / 3D-Druck VB-Ebene",
  "ANZ_MIT": "Anzahl der Mitarbeiter (Mantelbogen)",
  "ANZ_MITJAE": "Anzahl JAE",
  "Art der ge": "Art der geplanten Präsentation (Vortrag, Aussteller, Podiumsdiskussion etc.?)",
  "Art der ge31": "Art der geplanten Präsentation (Vortrag, Aussteller, Podiumsdiskussion etc.?)",
  "ATTR_TEXT": "Attribut neuer Platz",
  "AUS_NEMO_L": "Unternehmensgröße / Junge Unternehmen",
  "Ausgewählt": "Ausgewählt vom PT/BMWK",
  "Ausgewählt34": "Ausgewählt vom PT/BMWK",
  "Batteriete": "Batterietechnik TV-Ebene",
  "Batteriete21": "Batterietechnik VB-Ebene",
  "Big Data A": "Big Data Analyse TV-Ebene",
  "Big Data A5": "Big Data Analyse VB-Ebene",
  "Biotechnic": "Biotechnica VB-Ebene",
  "BULAND_AFS": "BL (AFS)",
  "Cloud Comp": "Cloud Computing TV-Ebene",
  "Cloud Comp4": "Cloud Computing VB-Ebene",
  "D_AAE": "Antrags eingang",
  "D_ABB": "Bewilligung",
  "D_XEFB1": "Erfolgsbeispiel angefragt",
  "D_XEFB2": "Erfolgsbeispiel bestätigt",
  "D_XEFB3": "Erfolgsbeispiel verneint",
  "D_XEFB4": "Erfolgsbeispiel in Arbeit",
  "D_XEFB5": "Erfolgsbeispiel Freigabe BMWK angefragt",
  "D_XEFB6": "Datum Erfolgsbeispiel veröffentlicht (letzer Eintrag)",
  "D_XYPM_A": "Datum Pressemitteilung",
  "D_YPM_A": "Datum Pressemitteilung",
  "DDSID_10": "DDSID_10",
  "Digitale W": "Digitale Wirtschaft und Gesellschaft (IKT) TV-Ebene",
  "Digitale W2": "Digitale Wirtschaft und Gesellschaft (IKT) VB-Ebene",
  "DA": "Datum Erfolgsbeispiel veröffentlicht (alle Einträge)",
  "Eignung pe": "Eignung persönlich verifiziert durch:",
  "Eignung pe38": "Eignung persönlich verifiziert durch:",
  "Elektromob": "Elektromobilität TV-Ebene",
  "Elektromob9": "Elektromobilität VB-Ebene",
  "Energie/Re": "Energie/Ress. Effizienz TV-Ebene",
  "Energie/Re12": "Energie/Ress. Effizienz VB-Ebene",
  "Erfolgsbei": "Erfolgsbeispiel VB-Ebene",
  "FachPack": "FachPack VB-Ebene",
  "Falls ja,": "Name Referent (NW) VB-Ebene",
  "Falls ja,25": "Referent (FuE) TV-Ebene",
  "FKZ": "FKZ",
  "FM_NUMMER": "Programm",
  "FormNext": "FormNext VB-Ebene",
  "FREMDKENNZ": "Projektform",
  "Gesundes L": "Gesundes Leben TV-Ebene",
  "Gesundes L17": "Gesundes Leben VB-Ebene",
  "GreenTech": "GreenTech VB-Ebene",
  "Grund der": "Grund der Absage des Zuwendungsempfängers",
  "Grund der33": "Grund der Absage des Zuwendungsempfängers",
  "Grund für": "Grund für Nicht-Auswahl des Zuwendungsempfängers",
  "Grund für35": "Grund für Nicht-Auswahl des Zuwendungsempfängers",
  "Handwerk /": "Handwerk / Installation (nur FuE) (TV-Ebene, \"zur Organisation\")",
  "Handwerksm": "Handwerksmesse VB-Ebene",
  "Hannover M": "Hannover Messe VB-Ebene",
  "Industrie": "Industrie 4.0 TV-Ebene",
  "Industrie3": "Industrie 4.0 VB-Ebene",
  "Innovation": "Innovationstag VB-Ebene",
  "Innovative": "Innovative Arbeitswelt TV-Ebene",
  "Innovative18": "Innovative Arbeitswelt VB-Ebene",
  "Intelligen": "Intelligente Mobilität TV-Ebene",
  "Intelligen8": "Intelligente Mobilität VB-Ebene",
  "IT-Sicherh": "IT-Sicherheit TV-Ebene",
  "IT-Sicherh15": "IT-Sicherheit VB-Ebene",
  "keine Kate": "keine Kategorie zutreffend TV-Ebene",
  "keine Kate24": "keine Kategorie zutreffend VB-Ebene",
  "KuK-Innova": "KUK-Innovationen (Technolog. Für bzw. von Kultur-, Medien-, u. Kreativwirtschaft) TV-Ebene",
  "KuK-Innova22": "KUK-Innovationen (Technolog. Für bzw. von Kultur-, Medien-, u. Kreativwirtschaft) VB-Ebene",
  "Künstliche": "Künstliche Intelligenz (KI) TV-Ebene",
  "Künstliche6": "Künstliche Intelligenz (KI) VB-Ebene",
  "Leichtbaut": "Leichtbautechnologien TV-Ebene",
  "Leichtbaut19": "Leichtbautechnologien VB-Ebene",
  "LFZ_TV_B": "TV Beginn",
  "LFZ_TV_E": "TV Ende",
  "Mikroelekt": "Mikroelektronik TV-Ebene",
  "Mikroelekt20": "Mikroelektronik VB-Ebene",
  "NACE": "NACE-Code (NW) Antragsebene",
  "NACE_LANG": "NACE-Code-Beschreibung (NW) Antragsebene",
  "NACECode.O": "NACE-Code (FuE) Organisationsebene",
  "Nachhaltig": "Nachhaltiges Wirtschaften / Green Economy TV-Ebene",
  "Nachhaltig11": "Nachhaltiges Wirtschaften / Green Economy VB-Ebene",
  "NAT_ZUORD": "nationale Zuordnung",
  "NETZWERKNA": "Netzwerk \"Kurzname\" FKZ_ZTP",
  "ORG_AFS": "Antragsteller (AFS)",
  "ORT_AFS": "Ort (AFS)",
  "PLZ_AFS": "PLZ (AFS)",
  "Präsentati": "Präsentation realisiert",
  "Präsentati26": "Präsentation nicht realisiert",
  "Präsentati36": "Präsentation realisiert",
  "Präsentati37": "Präsentation nicht realisiert",
  "sonstigeDW": "sonstige (Digitale Wirtschaft…) TV-Ebene",
  "sonstigeDW7": "sonstige (Digitale Wirtschaft…) VB-Ebene",
  "sonstigeIM": "sonstige (Intelligente Mobilität) TV-Ebene",
  "sonstigeIM10": "sonstige (Intelligente Mobilität) VB-Ebene",
  "sonstigeNW": "sonstige (nachhaltiges Wirtschaften...) TV-Ebene",
  "sonstigeNW13": "sonstige (nachhaltiges Wirtschaften...) VB-Ebene",
  "sonstigeZS": "sonstige (Zivile Sicherheit) TV-Ebene",
  "sonstigeZS16": "sonstige (Zivile Sicherheit) VB-Ebene",
  "STATUS_TV": "Status TV",
  "STATUS_VB": "Status VB",
  "STR_AFS": "Straße (AFS)",
  "T_XEFB6": "Erfolgsbeispiel veröffentlicht (JAHR; deutsch/englisch) (letzter Eintrag)",
  "T_XYPM_A": "Text Pressemitteilung",
  "T_YPM_A": "Text Pressemitteilung",
  "THEMA_AD": "TV Titel",
  "TA": "Erfolgsbeispiel veröffentlicht (JAHR; deutsch/englisch) (alle Einträge)",
  "VB_BEMERK": "Partnerländer",
  "VB_INHALT": "Inhalt / Kurzzusammenfassung",
  "VB_KURZNAM": "VB Kurzname",
  "VB_NUMMER": "VB Kennz.",
  "VB_PHASE": "Phase",
  "VB_TITEL": "VB Titel",
  "Wann wurde": "Wann wurde angefragt (Datum)?",
  "Wann wurde28": "Wann wurde angefragt (Datum)?",
  "weitere Fa": "weitere Fachmesse VB-Ebene",
  "Wer hat an": "Wer hat angefragt (Paraphe)?",
  "Wer hat an27": "Wer hat angefragt (Paraphe)?",
  "Wer war de": "Wer war der Ansprechpartner/Gesprächspartner?",
  "Wer war de29": "Wer war der Ansprechpartner/Gesprächspartner?",
  "WKNAAK_AFS": "Wahlkreisname (AFS)",
  "WKNRAK_AFS": "Wahlkreisnummer (AFS)",
  "Wofür wurd": "Wofür wurde angefragt (Name und Jahr der Veranstaltung)?",
  "Wofür wurd30": "Wofür wurde angefragt (Name und Jahr der Veranstaltung)?",
  "ZIM-Preis": "ZIM-Preis VB-Ebene",
  "Zivile Sic": "Zivile Sicherheit (inkl. IT) TV-Ebene",
  "Zivile Sic14": "Zivile Sicherheit (inkl. IT) VB-Ebene",
  "ZTP_KUERZ": "ZTP",
  "Zusage des": "Zusage des Zuwendungsempfängers",
  "Zusage des32": "Zusage des Zuwendungsempfängers",
};

export interface ZukunftstechnologieFeld {
  /** CSV-Spaltenname (gekuerzt, wie in der echten CSV). */
  csvColumn: string;
  /** Custom-Field-Name im Antrag-Record nach dem CSV-Merge (siehe schema-c.ts). */
  customField: string;
  /** Vollname aus der Labels-XLSX (z.B. "Kuenstliche Intelligenz (KI)"). */
  klartext: string;
  /** TV oder VB-Ebene. */
  ebene: 'tv' | 'vb';
  /** Default-Zuordnung zu einer der 5 Ueberkategorien. */
  defaultUeberKategorie: UeberkategorieId;
}

/** Zukunftstechnologie-Boolean-Spalten (col ~46-89 in schema-c-CSV). */
export const ZUKUNFTSTECHNOLOGIE_FELDER: ZukunftstechnologieFeld[] = [
  { csvColumn: "Digitale W", customField: "zt_digitale_wirtschaft_und_gesellschaft_ikt_tv", klartext: "Digitale Wirtschaft und Gesellschaft (IKT)", ebene: "tv", defaultUeberKategorie: "DT" },
  { csvColumn: "Digitale W_1", customField: "zt_digitale_wirtschaft_und_gesellschaft_ikt_vb", klartext: "Digitale Wirtschaft und Gesellschaft (IKT)", ebene: "vb", defaultUeberKategorie: "DT" },
  { csvColumn: "Industrie", customField: "zt_industrie_4_0_tv", klartext: "Industrie 4.0", ebene: "tv", defaultUeberKategorie: "IT" },
  { csvColumn: "Industrie_1", customField: "zt_industrie_4_0_vb", klartext: "Industrie 4.0", ebene: "vb", defaultUeberKategorie: "IT" },
  { csvColumn: "Cloud Comp", customField: "zt_cloud_computing_tv", klartext: "Cloud Computing", ebene: "tv", defaultUeberKategorie: "DT" },
  { csvColumn: "Cloud Comp_1", customField: "zt_cloud_computing_vb", klartext: "Cloud Computing", ebene: "vb", defaultUeberKategorie: "DT" },
  { csvColumn: "Big Data A", customField: "zt_big_data_analyse_tv", klartext: "Big Data Analyse", ebene: "tv", defaultUeberKategorie: "DT" },
  { csvColumn: "Big Data A_1", customField: "zt_big_data_analyse_vb", klartext: "Big Data Analyse", ebene: "vb", defaultUeberKategorie: "DT" },
  { csvColumn: "Künstliche", customField: "zt_kuenstliche_intelligenz_ki_tv", klartext: "Künstliche Intelligenz (KI)", ebene: "tv", defaultUeberKategorie: "DT" },
  { csvColumn: "Künstliche_1", customField: "zt_kuenstliche_intelligenz_ki_vb", klartext: "Künstliche Intelligenz (KI)", ebene: "vb", defaultUeberKategorie: "DT" },
  { csvColumn: "sonstigeDW", customField: "zt_sonstige_digitale_wirtschaft_tv", klartext: "sonstige (Digitale Wirtschaft…)", ebene: "tv", defaultUeberKategorie: "DT" },
  { csvColumn: "sonstigeDW_1", customField: "zt_sonstige_digitale_wirtschaft_vb", klartext: "sonstige (Digitale Wirtschaft…)", ebene: "vb", defaultUeberKategorie: "DT" },
  { csvColumn: "Intelligen", customField: "zt_intelligente_mobilitaet_tv", klartext: "Intelligente Mobilität", ebene: "tv", defaultUeberKategorie: "IT" },
  { csvColumn: "Intelligen_1", customField: "zt_intelligente_mobilitaet_vb", klartext: "Intelligente Mobilität", ebene: "vb", defaultUeberKategorie: "IT" },
  { csvColumn: "Elektromob", customField: "zt_elektromobilitaet_tv", klartext: "Elektromobilität", ebene: "tv", defaultUeberKategorie: "EU" },
  { csvColumn: "Elektromob_1", customField: "zt_elektromobilitaet_vb", klartext: "Elektromobilität", ebene: "vb", defaultUeberKategorie: "EU" },
  { csvColumn: "sonstigeIM", customField: "zt_sonstige_intelligente_mobilitaet_tv", klartext: "sonstige (Intelligente Mobilität)", ebene: "tv", defaultUeberKategorie: "IT" },
  { csvColumn: "sonstigeIM_1", customField: "zt_sonstige_intelligente_mobilitaet_vb", klartext: "sonstige (Intelligente Mobilität)", ebene: "vb", defaultUeberKategorie: "IT" },
  { csvColumn: "Nachhaltig", customField: "zt_nachhaltiges_wirtschaften_green_economy_tv", klartext: "Nachhaltiges Wirtschaften / Green Economy", ebene: "tv", defaultUeberKategorie: "EU" },
  { csvColumn: "Nachhaltig_1", customField: "zt_nachhaltiges_wirtschaften_green_economy_vb", klartext: "Nachhaltiges Wirtschaften / Green Economy", ebene: "vb", defaultUeberKategorie: "EU" },
  { csvColumn: "Energie/Re", customField: "zt_energie_ress_effizienz_tv", klartext: "Energie/Ress. Effizienz", ebene: "tv", defaultUeberKategorie: "EU" },
  { csvColumn: "Energie/Re_1", customField: "zt_energie_ress_effizienz_vb", klartext: "Energie/Ress. Effizienz", ebene: "vb", defaultUeberKategorie: "EU" },
  { csvColumn: "sonstigeNW", customField: "zt_sonstige_nachhaltiges_wirtschaften_tv", klartext: "sonstige (nachhaltiges Wirtschaften...)", ebene: "tv", defaultUeberKategorie: "EU" },
  { csvColumn: "sonstigeNW_1", customField: "zt_sonstige_nachhaltiges_wirtschaften_vb", klartext: "sonstige (nachhaltiges Wirtschaften...)", ebene: "vb", defaultUeberKategorie: "EU" },
  { csvColumn: "Zivile Sic", customField: "zt_zivile_sicherheit_inkl_it_tv", klartext: "Zivile Sicherheit (inkl. IT)", ebene: "tv", defaultUeberKategorie: "DT" },
  { csvColumn: "Zivile Sic_1", customField: "zt_zivile_sicherheit_inkl_it_vb", klartext: "Zivile Sicherheit (inkl. IT)", ebene: "vb", defaultUeberKategorie: "DT" },
  { csvColumn: "IT-Sicherh", customField: "zt_it_sicherheit_tv", klartext: "IT-Sicherheit", ebene: "tv", defaultUeberKategorie: "DT" },
  { csvColumn: "IT-Sicherh_1", customField: "zt_it_sicherheit_vb", klartext: "IT-Sicherheit", ebene: "vb", defaultUeberKategorie: "DT" },
  { csvColumn: "sonstigeZS", customField: "zt_sonstige_zivile_sicherheit_tv", klartext: "sonstige (Zivile Sicherheit)", ebene: "tv", defaultUeberKategorie: "DT" },
  { csvColumn: "sonstigeZS_1", customField: "zt_sonstige_zivile_sicherheit_vb", klartext: "sonstige (Zivile Sicherheit)", ebene: "vb", defaultUeberKategorie: "DT" },
  { csvColumn: "Gesundes L", customField: "zt_gesundes_leben_tv", klartext: "Gesundes Leben", ebene: "tv", defaultUeberKategorie: "LG" },
  { csvColumn: "Gesundes L_1", customField: "zt_gesundes_leben_vb", klartext: "Gesundes Leben", ebene: "vb", defaultUeberKategorie: "LG" },
  { csvColumn: "Innovative", customField: "zt_innovative_arbeitswelt_tv", klartext: "Innovative Arbeitswelt", ebene: "tv", defaultUeberKategorie: "IT" },
  { csvColumn: "Innovative_1", customField: "zt_innovative_arbeitswelt_vb", klartext: "Innovative Arbeitswelt", ebene: "vb", defaultUeberKategorie: "IT" },
  { csvColumn: "Leichtbaut", customField: "zt_leichtbautechnologien_tv", klartext: "Leichtbautechnologien", ebene: "tv", defaultUeberKategorie: "IT" },
  { csvColumn: "Leichtbaut_1", customField: "zt_leichtbautechnologien_vb", klartext: "Leichtbautechnologien", ebene: "vb", defaultUeberKategorie: "IT" },
  { csvColumn: "Mikroelekt", customField: "zt_mikroelektronik_tv", klartext: "Mikroelektronik", ebene: "tv", defaultUeberKategorie: "IT" },
  { csvColumn: "Mikroelekt_1", customField: "zt_mikroelektronik_vb", klartext: "Mikroelektronik", ebene: "vb", defaultUeberKategorie: "IT" },
  { csvColumn: "Batteriete", customField: "zt_batterietechnik_tv", klartext: "Batterietechnik", ebene: "tv", defaultUeberKategorie: "EU" },
  { csvColumn: "Batteriete_1", customField: "zt_batterietechnik_vb", klartext: "Batterietechnik", ebene: "vb", defaultUeberKategorie: "EU" },
  { csvColumn: "KuK-Innova", customField: "zt_kuk_innovationen_technolog_fuer_bzw_von_kultur_medien_u_krea_tv", klartext: "KUK-Innovationen (Technolog. Für bzw. von Kultur-, Medien-, u. Kreativwirtschaft)", ebene: "tv", defaultUeberKategorie: "IT" },
  { csvColumn: "KuK-Innova_1", customField: "zt_kuk_innovationen_technolog_fuer_bzw_von_kultur_medien_u_krea_vb", klartext: "KUK-Innovationen (Technolog. Für bzw. von Kultur-, Medien-, u. Kreativwirtschaft)", ebene: "vb", defaultUeberKategorie: "IT" },
  { csvColumn: "Additive F", customField: "zt_additive_fertigung_3d_druck_tv", klartext: "Additive Fertigung / 3D-Druck", ebene: "tv", defaultUeberKategorie: "IT" },
  { csvColumn: "Additive F_1", customField: "zt_additive_fertigung_3d_druck_vb", klartext: "Additive Fertigung / 3D-Druck", ebene: "vb", defaultUeberKategorie: "IT" },
];

/**
 * Substring-Heuristik fuer Stage-1-Fallback: matched TECHN_/BRANCHE_/
 * ANWEND_-Werte gegen Schluesselwoerter pro Ueberkategorie. Wird genutzt
 * wenn die ZT-Boolean-Spalten in einem Antrag leer sind (z.B. alte CSVs).
 */
export const KATEGORIE_KEYWORD_HEURISTIK: Record<UeberkategorieId, string[]> = {
  IT: [
    "industrie 4.0",
    "leichtbau",
    "mikroelektronik",
    "additive fertigung",
    "3d-druck",
    "mobilitaet",
    "mobilität",
    "innovative arbeit",
    "maschinenbau",
    "fertigung",
    "produktion",
    "werkstoff",
    "cfk",
    "fem",
  ],
  DT: [
    "ki",
    "künstliche intelligenz",
    "kuenstliche intelligenz",
    "ai",
    "big data",
    "cloud",
    "ikt",
    "digitale wirtschaft",
    "software",
    "algorithmus",
    "machine learning",
    "data science",
    "iot",
    "cybersicherheit",
    "it-sicherheit",
  ],
  EU: [
    "energie",
    "umwelt",
    "nachhaltig",
    "green",
    "elektromobil",
    "batterie",
    "ressourcen",
    "klima",
    "recycling",
    "photovoltaik",
    "solar",
    "wind",
    "erneuerbar",
    "wasserstoff",
    "co2",
  ],
  LG: [
    "gesund",
    "medizin",
    "pharma",
    "biotech",
    "pflege",
    "klinik",
    "diagnostik",
    "therapie",
    "biologie",
    "genom",
    "protein",
    "mikrobiom",
  ],
  NM: [
    "chemie",
    "physik",
    "materialforschung",
    "spektroskop",
    "messverfahren",
    "labor",
    "naturwissenschaft",
    "analytik",
    "simulation",
    "modellierung",
    "nanotechnologie",
    "quanten",
  ],
};
