project_id = "iqueifgygjqcianwmiyj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-enrollment]
    verify_jwt = false
  [functions.evaluate-prompt]
    verify_jwt = false
  [functions.guest-login]
    verify_jwt = false
  [functions.llm-proxy]
    verify_jwt = false
  [functions.save-user-key]
    verify_jwt = false
