/**
 * GENERIERT — nicht von Hand bearbeiten.
 *
 * Quelle: `docs/status-system/kuerzel-zuarbeit-20260724.csv`
 * Erzeuger: `scripts/gen-status-codes.mjs` (`npm run gen:status-codes`)
 *
 * Die Kürzel-Zuarbeit des Fachsystems: 505 Statuscodes mit ihrer
 * amtlichen Bezeichnung und der Angabe, **wer den Eintrag setzt**. Beides sind
 * Fremddaten und stehen deshalb hier, getrennt von unserer Kuration (Ordner,
 * Prominenz, Spine-Phase, Rang) in `seed-codes.ts`.
 *
 * `rollen: []` heißt **neutral: jeder darf setzen** — nicht „niemand". Ein
 * neutraler Eintrag ist unter jeder Rollenwahl sichtbar (siehe `rollen.ts`).
 */
import type { Rolle } from './typen';

export interface ZuarbeitCode {
  /** Code des Fachsystems ohne Spalten-Präfix (`XTEC` zu `D_XTEC`), NFC-normalisiert. */
  code: string;
  /** Bezeichnung wortgetreu aus der Zuarbeit — inklusive Abkürzungen und Tippfehler.
   *  Umformulieren würde die Wiedererkennung gegen das Fachsystem zerstören. */
  label: string;
  /** Wer den Eintrag setzt. Leer = neutral = jeder. */
  rollen: readonly Rolle[];
}

/** Reihenfolge = Reihenfolge der Zuarbeit (stabil für den Seed-Determinismus-Test). */
export const ZUARBEIT_CODES: readonly ZuarbeitCode[] = [
  { code: "XYT", label: "Tel.:", rollen: [] },
  { code: "COMP", label: "Compounddokument", rollen: [] },
  { code: "YG", label: "Beratungsgespräch bei VDI/VDE-IT", rollen: [] },
  { code: "YT", label: "Telefonat mit", rollen: [] },
  { code: "YE", label: "E-Mail", rollen: [] },
  { code: "YFO", label: "Eingang Foyer", rollen: [] },
  { code: "YB", label: "Brief", rollen: [] },
  { code: "YF", label: "Fax", rollen: [] },
  { code: "YJ", label: "juristisches Schreiben eingegangen", rollen: [] },
  { code: "YJE", label: "juristisches Schreiben ohne QS-Bedarf erstellt", rollen: ['jur'] },
  { code: "YJEQS", label: "juristisches Schreiben mit QS-Bedarf erstellt", rollen: ['jur'] },
  { code: "YJQ", label: "QS juristisches Schreiben erfolgt", rollen: ['jur'] },
  { code: "YJZ", label: "juristisches Schreiben wurde versendet", rollen: [] },
  { code: "XCARE", label: "Marker für kritisches Projekt in der Begleitung", rollen: [] },
  { code: "XJURB", label: "juristische Bearbeiter:in", rollen: [] },
  { code: "YZU", label: "Zustellungsurkunde an Ast/ZE", rollen: ['pa'] },
  { code: "YZUN", label: "Zustellung nicht möglich", rollen: [] },
  { code: "YZUD", label: "Zustellung an Person/Briefkasten/sonstiges", rollen: ['pa'] },
  { code: "YRP", label: "Rücknahme ist eingegangen -> zur Prüfung an AB", rollen: [] },
  { code: "YWSP", label: "Widerspruch ist eingegangen", rollen: [] },
  { code: "YWSP?", label: "Widerspruch ist unvollständig", rollen: ['jur'] },
  { code: "YWSP-", label: "Widerspruch ist unzulässig", rollen: ['ab'] },
  { code: "YKA", label: "Eingang Klage vor Bewilligung", rollen: [] },
  { code: "YKB", label: "Eingang Klage nach Bewilligung", rollen: [] },
  { code: "YW", label: "Wichtig", rollen: [] },
  { code: "HINT", label: "Bemerkung:", rollen: [] },
  { code: "ANT", label: "Termin für Nachlieferung", rollen: ['ab', 'fb'] },
  { code: "VME", label: "Vollmacht NWME/Berater mit Einschränkungen", rollen: [] },
  { code: "VOE", label: "Vollmacht NWME/Berater ohne Einschränkungen", rollen: [] },
  { code: "NA", label: "Eingang Änderung Firmendaten", rollen: [] },
  { code: "NE", label: "Änderung Firmendaten erledigt", rollen: [] },
  { code: "AKTK", label: "Aktennotiz kaufm. erstellt/ergänzt/keine Ergänzung", rollen: ['ab'] },
  { code: "AKTT", label: "Aktennotiz fachl. erstellt/ergänzt/keine Ergänzung", rollen: ['fb'] },
  { code: "AKTF", label: "Aktennotiz ist fertig (Grund (adm./fachl.))", rollen: ['ab', 'fb'] },
  { code: "AKTQ", label: "QS der Aktennotiz ohne Bescheid als Folge ist erfolgt", rollen: ['qs'] },
  { code: "AKTQB", label: "QS der Aktennotiz ist erfolgt - weiter mit Juristen", rollen: ['qs'] },
  { code: "AKTQZ", label: "QS Rückforderungs-/Erstattungsbetrag und Zinsen erfolgt", rollen: ['qs'] },
  { code: "ARK", label: "Rücknahmeempfehlung adm. erstellt/ergänzt/keine Ergänzung", rollen: ['ab'] },
  { code: "ART", label: "Rücknahmeempfehlung techn. erstellt/ergänzt/keine Ergänzung", rollen: ['fb'] },
  { code: "ARF", label: "Entwurf Rücknahmeempfehlung fertig", rollen: ['ab'] },
  { code: "ARQ-", label: "QS RNE zurück an AB/FB", rollen: ['qs'] },
  { code: "ARQ", label: "Rücknahmeempfehlung Qualitätssicherung", rollen: ['qs'] },
  { code: "ARZ", label: "Rücknahmeempfehlung an Ast", rollen: ['pa'] },
  { code: "ARR", label: "Termin Rücknahmeempfehlung", rollen: [] },
  { code: "AAR", label: "Antrag vom ASt zurückgezogen", rollen: ['ab'] },
  { code: "ARW", label: "Stellungnahme des Ast zur Rücknahmeempfehlung", rollen: [] },
  { code: "ABLK", label: "Ablehnung adm. erstellt/ergänzt/keine Ergänzung", rollen: ['ab'] },
  { code: "ABLT", label: "Ablehnung tech. erstellt/ergänzt/keine Ergänzung", rollen: ['fb'] },
  { code: "ABLF", label: "Entwurf Ablehnung fertig", rollen: ['ab', 'fb'] },
  { code: "XABLF", label: "\"alle\" Ablehnungen erstellt", rollen: ['ab', 'fb'] },
  { code: "ABLQ-", label: "QS Ablehnung QS zurück an AB/FB", rollen: ['qs'] },
  { code: "ABLQ", label: "Ablehnung Qualitätssicherung", rollen: ['qs'] },
  { code: "ABLJ", label: "Ablehnung juristische Qualitätssicherung", rollen: ['jur'] },
  { code: "ABLQS", label: "Finale Qualitätssicherung Ablehnung", rollen: ['qs'] },
  { code: "ABLZ", label: "Ablehnung an Ast", rollen: ['pa'] },
  { code: "AAA", label: "allgemeine Ablehnung", rollen: [] },
  { code: "ABL10", label: "10. Ablehnung an BMWK", rollen: ['pa'] },
  { code: "ABL10+", label: "10. Ablehnung Freigabe durch BMWK", rollen: ['pa'] },
  { code: "ABLD", label: "Termin Ablehnung bestandskräftig", rollen: ['pa'] },
  { code: "ABLW", label: "Widerspruch gegen Ablehnungsbescheid", rollen: [] },
  { code: "ABLWR", label: "Widerspruch zur Ablehnung zurückgezogen", rollen: [] },
  { code: "ABLWE", label: "pos/neg Widerspruchsbescheid erstellt", rollen: ['ab', 'fb'] },
  { code: "ABLWJ", label: "pos/neg Widerspruchsbescheid juristische QS", rollen: ['jur'] },
  { code: "ABLWQ", label: "pos/neg Widerspruchsbescheid QS ist erfolgt", rollen: ['qs'] },
  { code: "ABLWG", label: "Widerspruchsbescheid zur Kenntnisnahme / zur Freigabe ans BMWE", rollen: ['pa'] },
  { code: "ABLWG+", label: "Freigabe Widerspruchsbescheid vom BMWE erfolgt / nicht erforderlich", rollen: ['pa'] },
  { code: "ABLWZ", label: "negativer Widerspruchsbescheid nach Ablehnung", rollen: ['pa'] },
  { code: "ABLWD", label: "Termin Widerspruchsbescheid rechtskräftig", rollen: ['pa'] },
  { code: "AZBWZ", label: "positiver Widerspruchsbescheid nach Ablehnung", rollen: ['pa'] },
  { code: "STIP", label: "Stichprobe", rollen: [] },
  { code: "SPDOK", label: "Stichprobendokumente an ZG", rollen: [] },
  { code: "STZG", label: "Akte zur Stichprobe an ZG", rollen: [] },
  { code: "STIT", label: "Stichprobe zurück an IT", rollen: [] },
  { code: "STOK", label: "Stichprobe ok", rollen: [] },
  { code: "AA", label: "Antrag vom ASt unterschrieben", rollen: ['pa'] },
  { code: "AAE", label: "Antragseingang", rollen: ['pa'] },
  { code: "AAI", label: "Antragsimport aus ZIM-Foyer oder FZD (Vorgangscode: \"IDENTCODE FOYER\")", rollen: ['pa'] },
  { code: "AAE2", label: "Antragseingang 2", rollen: ['pa'] },
  { code: "ABK", label: "beantragte Kosten (Deckblatt Mantelbogen)", rollen: ['ab'] },
  { code: "ADV", label: "Antrag in C16 eingestellt", rollen: ['pa'] },
  { code: "AE", label: "Eingangsbestätigung an Ast", rollen: ['pa'] },
  { code: "AUS", label: "Unternehmen in Schwiergigkeiten", rollen: ['ab'] },
  { code: "ANRD", label: "Nachrangdarlehen vorhanden - (nicht) i.O.", rollen: ['ab'] },
  { code: "ALS", label: "TB ohne (weitere) Nachforderungen", rollen: ['fb'] },
  { code: "ALSB", label: "BB ohne (weitere) Nachforderungen", rollen: ['ab'] },
  { code: "ALT", label: "Brief NF von BB angelegt/ergänzt", rollen: ['ab'] },
  { code: "ALU", label: "Brief NF von TB angelegt/ergänzt", rollen: ['fb'] },
  { code: "ALF", label: "Nachforderung fertig für QS", rollen: ['ab', 'fb'] },
  { code: "ALQ", label: "NF von PL gelesen", rollen: ['qs'] },
  { code: "AN", label: "NF an ASt", rollen: ['ab', 'fb', 'qs'] },
  { code: "ANM", label: "Mahnung Nachforderung", rollen: ['ab', 'fb'] },
  { code: "AL", label: "Nachlieferung Eingang", rollen: [] },
  { code: "AMA", label: "Mitarbeiter Anzahl Anlage 1", rollen: ['ab'] },
  { code: "AT4", label: "Gutachten technisch fertig", rollen: ['fb'] },
  { code: "AK4", label: "Gutachten kaufmännisch fertig", rollen: ['ab'] },
  { code: "XKS", label: "DL-Gutachten fertig - FB/AB", rollen: ['ab', 'fb'] },
  { code: "AQ4-", label: "fachliche QS zurück an FB", rollen: ['qs'] },
  { code: "AQ4", label: "fachliche QS fertig", rollen: ['qs'] },
  { code: "QS-", label: "kaufmännische QS zurück an AB", rollen: ['qs'] },
  { code: "QS", label: "kaufmännische QS erfolgt", rollen: ['qs'] },
  { code: "XQS", label: "DL-Gutachten QS fertig", rollen: ['qs'] },
  { code: "ABX", label: "Bewilligung ausgestezt", rollen: ['qs'] },
  { code: "AB", label: "Bewilligungsempfehlung durch Haushaltsbeauftrage/Titelverantwortliche", rollen: ['qs'] },
  { code: "ABB", label: "Bewilligung", rollen: ['qs'] },
  { code: "AZ1", label: "Erstentscheidung", rollen: [] },
  { code: "AZBE", label: "Zuwendungsbescheid erstellt", rollen: ['ab'] },
  { code: "AZBQ", label: "Zuwendungsbescheid Qualitätssicherung", rollen: ['qs'] },
  { code: "AZBZ", label: "Bewilligung an ZE", rollen: ['pa'] },
  { code: "AZW", label: "Widerspruch ZuwBescheid eingegangen", rollen: [] },
  { code: "AZWR", label: "Widerspruch ZuwBescheid zurückgezogen", rollen: [] },
  { code: "AZWE", label: "Widerspruchsbescheid erstellt", rollen: [] },
  { code: "AZWJ", label: "Widerspruchsbescheid juristische QS erfolgt", rollen: ['jur'] },
  { code: "AZWQ", label: "Widerspruchsbescheid QS durch PL erfolgt (pos/neg)", rollen: ['qs'] },
  { code: "AZWG", label: "Widerspruchsbescheid zur Kenntnissnahme ans BMWK", rollen: ['pa'] },
  { code: "AZWG+", label: "Rückfragen/Hinweise vom BMWK", rollen: ['pa'] },
  { code: "AZWA", label: "negativer Widerspruchsbescheid", rollen: ['pa'] },
  { code: "AZWZ", label: "positiver Widerspruchsbescheid", rollen: ['pa'] },
  { code: "AZWD", label: "Frist Klage Widerspruchsbescheid", rollen: ['pa'] },
  { code: "RZA", label: "Grund für Rücknahme des Zuw.bescheides eingegangen", rollen: [] },
  { code: "RZE", label: "Rücknahmebescheid des ZuwBescheides erstellt", rollen: ['ab', 'fb'] },
  { code: "RZJ", label: "Rücknahmebescheid juristische QS erfolgt", rollen: ['jur'] },
  { code: "RZQ", label: "Rücknahmebescheid QS ist erfolgt", rollen: ['qs'] },
  { code: "RZG", label: "Rücknahmebescheid ans BMWK", rollen: ['pa'] },
  { code: "RZG+", label: "Rückfragen/Hinweise vom BMWK", rollen: ['pa'] },
  { code: "RZZ", label: "Rücknahmebescheid an ZE", rollen: ['pa'] },
  { code: "ABE", label: "Eingang Empfangsbestätigung", rollen: [] },
  { code: "AFUE", label: "FKZ zum zugehörigen FuE", rollen: ['pa'] },
  { code: "ADL1", label: "FKZ vom ersten DL-Antrag", rollen: ['pa'] },
  { code: "ADL2", label: "FKZ vom ersten DL-Folgeantrag", rollen: ['pa'] },
  { code: "ADL3", label: "FKZ vom zweiten DL-Folgeantrag", rollen: ['pa'] },
  { code: "XIZ", label: "Irrläufer an richtigen PT", rollen: ['pa'] },
  { code: "TG", label: "voraussichtlicher Termin DL-GA", rollen: ['ab', 'fb'] },
  { code: "DME", label: "Bescheinigung erstellt", rollen: [] },
  { code: "DMB", label: "Bescheinigung an ZE versandt", rollen: ['ab'] },
  { code: "DMDB", label: "Eintrag in de-minimis-DB ist erfolgt", rollen: ['pa'] },
  { code: "DMVN", label: "bitte de-minimis-Wert in de-minimis-DB aktualisieren", rollen: ['ab', 'qs'] },
  { code: "DMDB2", label: "Aktualisierung in de-minimis-DB ist erfolgt", rollen: ['pa'] },
  { code: "SA", label: "Antrag auf Entsperrung von ....", rollen: [] },
  { code: "SFB", label: "fachliche Prüfung erforderlich", rollen: ['fb'] },
  { code: "SN", label: "Nachforderung/Rückfragen zur Entsperrung", rollen: ['ab', 'fb'] },
  { code: "SL", label: "Eingang Nachlieferung zur Entsperrung", rollen: [] },
  { code: "ST", label: "techn. Bearbeitung Entsperrung erledigt", rollen: ['fb'] },
  { code: "SK", label: "kaufm. Bearbeitung Entsperrung erledigt", rollen: ['ab'] },
  { code: "SZ", label: "Mitteilung an ZE über Entsperrung von ...", rollen: ['ab', 'fb'] },
  { code: "SZX", label: "Mitteilung Sperre wird nicht aufgehoben an ZE", rollen: ['ab', 'fb'] },
  { code: "ÄA", label: "Eingang Änderungsantrag über ...", rollen: [] },
  { code: "ÄN", label: "Nachforderung/Rückfragen zum Änderungsantrag", rollen: ['ab', 'fb'] },
  { code: "ÄL", label: "Nachlieferung zum Änderungsantrag", rollen: [] },
  { code: "ÄT", label: "Änderung techn. bearbeitet", rollen: ['fb'] },
  { code: "ÄK", label: "Änderung kaufm. bearbeitet", rollen: ['ab'] },
  { code: "ÄQ", label: "Änderung bewilligt", rollen: ['qs'] },
  { code: "ÄAB", label: "Aufstockung vom Haushaltsbeauftragten bewilligt", rollen: ['qs'] },
  { code: "ÄZ", label: "Änderungsbescheid an ZE", rollen: ['pa'] },
  { code: "ÄZX", label: "Bewilligung ohne Bescheid", rollen: ['qs', 'pa'] },
  { code: "ÄAZ", label: "Ablehnung/Rücknahme des Änderungsantrags an ZE", rollen: ['pa'] },
  { code: "LA", label: "Antrag auf Laufzeitänderung", rollen: [] },
  { code: "LN", label: "Nachforderung/Rückfragen zur Laufzeitänderung", rollen: ['ab', 'fb'] },
  { code: "LL", label: "Nachlieferung zur Laufzeitänderung", rollen: [] },
  { code: "LT", label: "Laufzeitänderung techn. bearbeitet", rollen: ['fb'] },
  { code: "LK", label: "Laufzeitänderung kaufm. bearbeitet", rollen: ['ab'] },
  { code: "LQ", label: "Laufzeitänderung bewilligt", rollen: ['qs'] },
  { code: "LZ", label: "Änderungsbescheid Laufzeit an ZE", rollen: ['pa'] },
  { code: "LZX", label: "Bewilligung ohne Bescheid", rollen: ['qs', 'pa'] },
  { code: "LAZ", label: "Ablehnung/Rücknahme der Laufzeitänderung an ZE", rollen: ['pa'] },
  { code: "MVA", label: "Antrag auf Mittelverschiebung", rollen: [] },
  { code: "MVN", label: "Nachforderungen/Rückfragen zur Mittelverschiebung", rollen: ['ab', 'fb'] },
  { code: "MVL", label: "Nachlieferung zur Mittelverschiebung", rollen: [] },
  { code: "MVT", label: "Mittelverschiebung techn. bearbeitet", rollen: ['fb'] },
  { code: "MVK", label: "Mittelverschiebung kaufm. bearbeitet", rollen: ['ab'] },
  { code: "MVQ", label: "Mittelverschiebung bewilligt", rollen: ['qs'] },
  { code: "MVZ", label: "Mittelverschiebung an ZE", rollen: ['pa'] },
  { code: "MVX", label: "Mittelverschiebung ist nicht erforderlich/ohne Bescheid", rollen: ['qs', 'pa'] },
  { code: "MVAZ", label: "Ablehnung/Rücknahme der Mittelverschiebung an ZE", rollen: ['pa'] },
  { code: "ÄW", label: "Widerspruch Änderungsbescheid", rollen: [] },
  { code: "ÄAW", label: "Widerspruch gegen die Ablehnung eines Änderungsantrages", rollen: [] },
  { code: "ÄAWR", label: "Widerspruch Änderung zurückgezogen", rollen: [] },
  { code: "ÄAWE", label: "Widerspruchsbescheid erstellt", rollen: ['ab', 'fb'] },
  { code: "ÄAWJ", label: "Widerspruchsbescheid juristische QS erfolgt", rollen: ['jur'] },
  { code: "ÄAWQ", label: "Widerspruchsbescheid QS durch PL erfolgt (ÄK/LK/MVK)", rollen: ['qs'] },
  { code: "ÄAWA", label: "negativer Widerspruchsbescheid", rollen: ['pa'] },
  { code: "ÄAWZ", label: "positiver Widerspruchsbescheid", rollen: ['pa'] },
  { code: "ÄAWD", label: "Frist Klage Widerspruchsbescheid", rollen: ['pa'] },
  { code: "ZA1", label: "Termin 1. ZA", rollen: ['ab', 'qs'] },
  { code: "GA", label: "Eingang Zahlungsanforderung", rollen: [] },
  { code: "GN", label: "Nachforderung/Rückfragen zur ZA", rollen: ['ab', 'fb'] },
  { code: "GL", label: "Nachlieferung zur ZA", rollen: [] },
  { code: "GKS", label: "kaufm. Signierung ZA erfolgt", rollen: ['ab'] },
  { code: "GTS", label: "techn. Signierung ZA erfolgt", rollen: ['fb'] },
  { code: "GZ", label: "Auszahlung erfolgt", rollen: ['qs'] },
  { code: "GZ-", label: "Auszahlung konnte nicht erfolgen; Grund:", rollen: ['qs'] },
  { code: "GZX", label: "ZA nicht ausgeführt/ungültig", rollen: ['qs'] },
  { code: "ABA", label: "Projekt von ZE abgebrochen", rollen: [] },
  { code: "ABV", label: "ZE verzichtet auf Zuwendung ohne Mittelabfluss", rollen: ['ab', 'qs'] },
  { code: "IA", label: "Kenntnisnahme von Insolvenz", rollen: [] },
  { code: "IVW1", label: "Name des Insolvenzverwalters vor Eröffnung", rollen: ['ab', 'qs', 'jur'] },
  { code: "IER", label: "Eröffnung des Insolvenzverfahrens", rollen: [] },
  { code: "IVW2", label: "Name des Sachwalters", rollen: ['ab', 'qs', 'jur'] },
  { code: "IDFA", label: "Termin zur Forderungsanmeldung", rollen: ['pa'] },
  { code: "IFAE", label: "Forderungsanmeldung erstellt", rollen: ['ab', 'fb'] },
  { code: "IFAJ", label: "Forderungsanmeldung juristische QS erfolgt", rollen: ['jur'] },
  { code: "IFAZ", label: "Forderungsanmeldung versandt", rollen: ['pa'] },
  { code: "IFA", label: "Forderungsanmeldung b. RA", rollen: ['pa'] },
  { code: "IPFA", label: "Verfahren zur Prüfung der FA", rollen: ['ab', 'qs'] },
  { code: "GAM1", label: "Erinnerung an ZA", rollen: [] },
  { code: "GAM2", label: "Mahnung ZA", rollen: [] },
  { code: "VBM1", label: "Erinnerung VN-Sach", rollen: [] },
  { code: "VZM1", label: "Erinnerung VN-Zahl", rollen: [] },
  { code: "VBM2", label: "Mahnung VN-Sach", rollen: [] },
  { code: "VZM2", label: "Mahnung VN-Zahl", rollen: [] },
  { code: "ABRWE", label: "Anhörung zum Widerruf durch AB erstellt / Juristen erstellt+QS", rollen: ['ab', 'qs', 'jur'] },
  { code: "ABRWJ", label: "Anh z Wid QS juristisch erfolgt/nicht notwendig", rollen: ['jur'] },
  { code: "ABRWQ", label: "Anhörung zum Widerruf QS durch PL erfolgt", rollen: ['qs'] },
  { code: "ABRWZ", label: "Anhörung zum Widerruf an ZE", rollen: ['pa'] },
  { code: "ABRWD", label: "Termin Anhörungsfrist abgelaufen", rollen: ['pa'] },
  { code: "ABRWL", label: "Stellungnahme zur Anh z Wid eingegangen", rollen: [] },
  { code: "ABRWE2", label: "erweiterte Anhörung zum Widerruf durch Juristen erstellt", rollen: ['jur'] },
  { code: "ABRWQ2", label: "erweiterte Anhörung zum Widerruf QS durch PL erfolgt", rollen: ['qs'] },
  { code: "ABRWZ2", label: "erweiterte Anhörung zum Widerruf an ZE", rollen: ['pa'] },
  { code: "ABRWD2", label: "Termin erweiterte Anhörungsfrist abgelaufen", rollen: [] },
  { code: "ABRWL2", label: "Stellungnahme zur erweiterten Anh z Wid eingegangen", rollen: [] },
  { code: "WRE", label: "Widerruf erstellt", rollen: ['ab', 'fb'] },
  { code: "WRQ", label: "QS des Widerrufs (Art) durch PL erfolgt", rollen: ['qs'] },
  { code: "WRZG", label: "Widerruf ans BMWK", rollen: ['pa'] },
  { code: "WRZ", label: "Widerruf an ZE (Art)", rollen: ['pa'] },
  { code: "WRD", label: "Frist Einlegung Rechtsbehelf zum Widerruf", rollen: [] },
  { code: "WRBE", label: "Empfangsbestätigung Widerruf im IT", rollen: [] },
  { code: "WRW", label: "Widerspruch ZE gegen Widerruf (Art)", rollen: [] },
  { code: "WRWR", label: "Widerspruch zurückgezogen", rollen: [] },
  { code: "WRWE", label: "Widerspruchsbescheid erstellt (Jurist)", rollen: ['jur'] },
  { code: "WRWJ", label: "Widerspruchsbescheid QS juristisch erfolgt", rollen: ['jur'] },
  { code: "WRWQ", label: "Widerspruchsbescheid QS durch PL erfolgt", rollen: ['qs'] },
  { code: "WRWZG", label: "Widerspruchsbescheid ans BMWK", rollen: ['pa'] },
  { code: "WRWZG+", label: "Freigabe durch BMWK", rollen: ['pa'] },
  { code: "WRWA", label: "negativer Widerspruchsbescheid an ZE", rollen: ['pa'] },
  { code: "WRWZ", label: "positiver Widerspruchsbescheid an ZE", rollen: ['pa'] },
  { code: "WRWD", label: "Frist Klage Widerspruch", rollen: [] },
  { code: "WME", label: "Mitteilung Aussetzung/Beendigung Widerrufsverfahren erstellt", rollen: ['ab', 'fb'] },
  { code: "WMJ", label: "Mitteilung Widerrufsverfahren juritische QS erfolgt", rollen: ['jur'] },
  { code: "WMA", label: "Mitteilung Aussetzung Widerrufsverfahren an ZE", rollen: ['pa'] },
  { code: "WMZ", label: "Mitteilung Beendigung Widerrufsverfahren an ZE", rollen: ['pa'] },
  { code: "VU", label: "Teilvorhaben beendet", rollen: [] },
  { code: "TVN", label: "Termin Verwendungsnachweis", rollen: ['ab', 'fb'] },
  { code: "VBF", label: "Fristverlängerung VN-Sach", rollen: ['ab', 'fb'] },
  { code: "VZF", label: "Fristverlängerung VN-Zahl", rollen: ['ab', 'fb'] },
  { code: "VBE", label: "Eingang VN-Sach", rollen: [] },
  { code: "VZE", label: "Eingang VN-Zahl", rollen: [] },
  { code: "VN", label: "Nachforderung/Rückfragen zum VN", rollen: ['ab', 'fb'] },
  { code: "VL", label: "Eingang Nachlieferung zum VN", rollen: [] },
  { code: "VPC", label: "kaufm. Vorprüfung erfolgt", rollen: ['ab'] },
  { code: "VBT", label: "VN-Sach geprüft", rollen: ['fb'] },
  { code: "MVP", label: "Restmittel ausgebucht", rollen: ['ab'] },
  { code: "VZK", label: "VN-Zahl geprüft", rollen: ['ab'] },
  { code: "VQK-", label: "VN zurück an AB", rollen: ['qs'] },
  { code: "VQK", label: "VN-Qualitätsicherung kaufm.", rollen: ['ab'] },
  { code: "VVZ", label: "VN-Ergebnis an ZE", rollen: ['ab', 'qs'] },
  { code: "VRR", label: "Termin Rückzahlung", rollen: [] },
  { code: "VRM", label: "Mahnung Rückzahlung", rollen: [] },
  { code: "VRE", label: "Eingang Rückzahlung inkl. Zinsen", rollen: [] },
  { code: "VRAE", label: "Aufrechnung erstellt", rollen: ['ab', 'fb'] },
  { code: "VRAJ", label: "Aufrechnung juristische QS erfolgt", rollen: ['jur'] },
  { code: "VRAZ", label: "Aufrechnung an ZE", rollen: ['pa'] },
  { code: "VRA", label: "Verrechnung ist erfolgt", rollen: ['ab'] },
  { code: "AVK", label: "Schlussvermerk vor Bewilligung vom AB signiert", rollen: ['ab'] },
  { code: "VVK", label: "Schlussvermerk vom AB signiert", rollen: ['ab'] },
  { code: "VV", label: "Schlussvermerk", rollen: ['qs'] },
  { code: "VAZ", label: "Archivierungsdatum", rollen: ['pa'] },
  { code: "VAK", label: "Akte im Keller", rollen: ['pa'] },
  { code: "VAR", label: "Akte archiviert", rollen: ['pa'] },
  { code: "DLP", label: "DL-Stichprobe positives Ergebnis", rollen: ['ab', 'fb'] },
  { code: "DLN", label: "DL-Stichprobe negatives Ergebnis", rollen: ['ab', 'fb'] },
  { code: "DLSR", label: "DL-Stichprobe realisiert", rollen: ['ab', 'fb'] },
  { code: "DLSP", label: "DL-Stichprobe vorgesehen", rollen: ['ab', 'fb'] },
  { code: "ADS", label: "FKZ der Durchführbarkeitsstudie", rollen: ['pa'] },
  { code: "ABLWT", label: "techn. Ablehnung Widerspruch Ablehnungsbescheid", rollen: ['fb'] },
  { code: "ABLWK", label: "kaufm. Ablehnung Widerspruch Ablehnungsbescheid", rollen: ['ab'] },
  { code: "ABLWH", label: "Widerspruchsbescheid geprüft durch HH-Beauftragten", rollen: ['qs'] },
  { code: "AADP", label: "Auftrag an Dritte positiv", rollen: ['ab', 'fb'] },
  { code: "AR", label: "Antrag mit Risiko", rollen: ['ab', 'fb'] },
  { code: "AVU", label: "VerbundUmsatz laut Anlage 1", rollen: ['ab'] },
  { code: "AVB", label: "VerbundBilanz laut Anlage 1", rollen: ['ab'] },
  { code: "AUF1", label: "Erste Aufstockung", rollen: ['pa'] },
  { code: "AUF2", label: "Zweite Aufstockung", rollen: ['pa'] },
  { code: "WK", label: "Wahlkreis beachten!", rollen: [] },
  { code: "GK", label: "kaufm. Bearbeitung ZA erfolgt", rollen: ['ab'] },
  { code: "GT", label: "techn. Bearbeitung ZA erfolgt", rollen: ['fb'] },
  { code: "GSP", label: "Stichprobe ZA vorgesehen", rollen: ['ab', 'fb'] },
  { code: "GSP+", label: "Stichprobe positiv", rollen: ['ab', 'fb'] },
  { code: "GSP-", label: "Stichprobe negativ", rollen: ['ab', 'fb'] },
  { code: "GSPM", label: "Maßnahme erfolgt", rollen: ['ab', 'fb'] },
  { code: "GSTAT", label: "unvollst. ZA Statistik", rollen: ['ab'] },
  { code: "ZBM1", label: "erste Erinnerung Zwischenbericht", rollen: [] },
  { code: "ZBM2", label: "zweite Erinnerung Zwischenbericht", rollen: [] },
  { code: "ZBM3", label: "Mahnung Zwischenbericht", rollen: [] },
  { code: "ZBE", label: "Eingang Zwischenbericht", rollen: [] },
  { code: "ZBN", label: "Nachforderung/Rückfragen zum Zwischenbericht", rollen: ['ab', 'fb'] },
  { code: "ZBL", label: "Nachlieferungen zum Zwischenbericht", rollen: [] },
  { code: "ZBT", label: "techn. Prüfung Zwischenbericht erledigt", rollen: ['fb'] },
  { code: "ZBK", label: "kaufm. Prüfung Zwischenbericht erledigt", rollen: ['ab'] },
  { code: "ZBZ", label: "Info an ZE über Prüfung ZB", rollen: ['ab', 'fb'] },
  { code: "ABRK", label: "Brief Abbruchempfehlung kaufm.", rollen: ['ab'] },
  { code: "ABRT", label: "Brief Abbruchempfehlung techn.", rollen: ['fb'] },
  { code: "ABRQ", label: "Brief Abbruchempfehlung endlesen", rollen: ['qs'] },
  { code: "ABRZ", label: "Brief Abbruchempfehlung an ZE", rollen: ['ab', 'fb', 'qs'] },
  { code: "ABRD", label: "Anhörungsfrist Abbruchempfehlung", rollen: [] },
  { code: "ABRW", label: "Widerspruch ZE gegen Abbruchempfehlung", rollen: [] },
  { code: "ABRWK", label: "Brief zu Widerspruch kaufm. erstellt", rollen: ['ab'] },
  { code: "ABRWT", label: "Brief zu Widerspruch techn. erstellt", rollen: ['fb'] },
  { code: "VOBP", label: "Vor-Ort-Besuch geplant", rollen: ['ab', 'fb', 'qs'] },
  { code: "VOBA", label: "Vor-Ort-Besuch angekündigt", rollen: ['ab', 'fb', 'qs'] },
  { code: "VOBB", label: "Termin VOB bestätigt", rollen: ['ab', 'fb', 'qs'] },
  { code: "VOBT", label: "Termin des VOB (Anlass; Uhrzeit/Dauer; AB/FB; dig/präs)", rollen: ['ab', 'fb', 'qs'] },
  { code: "VOBV", label: "VOB-Bericht vorbereitet/angelegt", rollen: ['pa'] },
  { code: "VOBR", label: "Vor-Ort-Besuch realisiert", rollen: ['ab', 'fb', 'qs'] },
  { code: "VOBN", label: "Nachforderung/Rückfragen zum VOB", rollen: ['ab', 'fb', 'qs'] },
  { code: "VOBL", label: "Nachlieferung zum VOB", rollen: [] },
  { code: "VOBF", label: "VOB-Bericht fertiggestellt", rollen: ['ab', 'fb'] },
  { code: "VOBQ", label: "VOB-Bericht Qualitätssicherung", rollen: ['qs'] },
  { code: "VOBZ", label: "Zensierung des Vor-Ort-Besuchs", rollen: ['ab', 'fb', 'qs'] },
  { code: "VOBDB", label: "VOB-Bericht in DB", rollen: ['ab', 'fb', 'qs'] },
  { code: "VQT", label: "VN-Qualitätssicherung fachl.", rollen: ['fb', 'qs'] },
  { code: "TOP", label: "erfolgreiches Beispiel", rollen: ['ab', 'fb'] },
  { code: "FLOP", label: "schlechtes Beispiel", rollen: ['ab', 'fb'] },
  { code: "IWS", label: "Informationsworkshop", rollen: [] },
  { code: "YPM", label: "Pressemitteilung:", rollen: [] },
  { code: "AK", label: "ausländischer Koordinator:", rollen: ['ab', 'fb'] },
  { code: "WIN", label: "Wechsel int/nat", rollen: [] },
  { code: "NWZV", label: "Hinweis auf NW Zusatzverträge", rollen: ['pa'] },
  { code: "NWSP", label: "Netzwerksprecher", rollen: [] },
  { code: "NWKB", label: "Netzwerkkurzbeschreibung freigegeben", rollen: [] },
  { code: "INFOB", label: "Infobrief an NWP", rollen: [] },
  { code: "SAAE", label: "Eingang Skizze", rollen: ['pa'] },
  { code: "SKUR", label: "Skizzentitel:", rollen: ['pa'] },
  { code: "SART", label: "INM; INF; iINM; iINF", rollen: ['pa'] },
  { code: "SDE", label: "Eingangsbestätigung Skizze an Ast", rollen: ['pa'] },
  { code: "SDTB", label: "Technischer Bearbeiter", rollen: ['qs'] },
  { code: "ST4", label: "Skizzenbewertung fertig", rollen: ['fb'] },
  { code: "ASÜ", label: "Überarbeitungshinweis: nicht im Format des Skizzenformulars", rollen: ['fb'] },
  { code: "ASB", label: "Befürwortung Skizze an Ast", rollen: ['fb'] },
  { code: "ASV", label: "Befürwortung Skizze unter Vorbehalt", rollen: ['fb'] },
  { code: "ASA", label: "Ablehnung Skizze an Ast", rollen: ['fb'] },
  { code: "SANT", label: "Zur Skizze ist ein Antrag eingegangen", rollen: ['pa'] },
  { code: "NWB", label: "Netzwerkbesuch (Bemerkung/Grund)", rollen: ['ab', 'fb', 'qs'] },
  { code: "AUFD", label: "Termin Auflagen", rollen: ['ab', 'fb'] },
  { code: "AUFE", label: "Eingang zu Auflagen", rollen: [] },
  { code: "AUFN", label: "Nachforderung zu Auflagen", rollen: ['ab', 'fb'] },
  { code: "AUFL", label: "Nachlieferung zu Auflagen", rollen: [] },
  { code: "AUFZ", label: "Auflage erfüllt, Info an ZE", rollen: ['ab', 'fb', 'qs'] },
  { code: "ZBD", label: "Termin Zwischenbericht", rollen: [] },
  { code: "LBD1", label: "Termin Leistungsbestätigung 1", rollen: [] },
  { code: "LBD2", label: "Termin Leistungsbestätigung 2", rollen: [] },
  { code: "LBD3", label: "Termin Leistungsbestätigung 3", rollen: [] },
  { code: "LBE1", label: "Eingang Leistungsbestätigung 1", rollen: [] },
  { code: "LBE2", label: "Eingang Leistungsbestätigung 2", rollen: [] },
  { code: "LBE3", label: "Eingang Leistungsbestätigung 3", rollen: [] },
  { code: "LBN", label: "Nachforderung/Rückfragen Leistungsbestätigung", rollen: ['ab'] },
  { code: "LBL", label: "Nachlieferung Leistungsbestätigung", rollen: [] },
  { code: "LBK1", label: "Leistungsbestätigung 1 kaufm. geprüft", rollen: ['ab'] },
  { code: "LBK2", label: "Leistungsbestätigung 2 kaufm. geprüft", rollen: ['ab'] },
  { code: "LBK3", label: "Leistungsbestätigung 3 kaufm. geprüft", rollen: ['ab'] },
  { code: "BAKE", label: "Eingang Bestätigung ausl. Koordinator", rollen: [] },
  { code: "BAKT", label: "Bestätigung ausl. Koordinator fachl. geprüft", rollen: ['fb'] },
  { code: "BAKK", label: "Bestätigung ausl. Koordinator kaufm. geprüft", rollen: ['ab'] },
  { code: "ZVE", label: "Eingang Zusatzvertrag", rollen: [] },
  { code: "ZVN", label: "Nachforderung zum Zusatzvertrag", rollen: ['ab', 'fb'] },
  { code: "ZVL", label: "Nachlieferung zum Zusatzvertrag", rollen: [] },
  { code: "ZVT", label: "Beurteilung durch TB erfolgt; an PL", rollen: ['fb'] },
  { code: "ZVQ", label: "QS der Entscheidung", rollen: ['qs'] },
  { code: "ZVZ", label: "Entscheidung an ZE per E-Mail", rollen: [] },
  { code: "IFAQ", label: "anzumeldene Forderung und Zinsen geprüft", rollen: ['ab'] },
  { code: "DFE", label: "Verdacht auf Doppelförderung", rollen: ['ab', 'fb', 'qs'] },
  { code: "DFA", label: "Verdacht nach Korrektur der Daten aufgehoben", rollen: ['ab', 'fb', 'qs'] },
  { code: "DFB", label: "Anhörung zur DoF muss erstellt werden", rollen: ['ab', 'fb', 'qs'] },
  { code: "DFEXT", label: "Abwicklung Doppelförderung anderer PT", rollen: ['ab', 'fb', 'qs'] },
  { code: "DFINT", label: "Abwicklung Doppelförderung VDIVDE", rollen: ['ab', 'fb', 'qs'] },
  { code: "DFU", label: "Vorgang Doppelförderung beendet", rollen: ['ab', 'fb', 'qs'] },
  { code: "AUFM", label: "Mahnung von Auflagen", rollen: ['ab', 'fb'] },
  { code: "LBM1", label: "Erinnerung Leistungsbestätigung", rollen: [] },
  { code: "LBM2", label: "Mahnung Leistungsbestätigung", rollen: [] },
  { code: "ABRWJ2", label: "erweiterte Anhörung zum Widerruf QS juristisch erfolgt", rollen: ['jur'] },
  { code: "PBP", label: "Projekt-Besuch geplant/gewünscht", rollen: ['ab', 'fb'] },
  { code: "PBT", label: "Termin für Projekt-Besuch", rollen: ['ab', 'fb'] },
  { code: "PBR", label: "Projekt-Besuch realisiert", rollen: ['ab', 'fb'] },
  { code: "PBQ", label: "Projekt-Besuch-Bericht QS", rollen: ['qs'] },
  { code: "PBU", label: "Unstimmigkeiten beim Projekt-Besuch", rollen: ['ab', 'fb'] },
  { code: "PBDB", label: "Vermerk in Datenbank (inkl. Unterschrift durch QS)", rollen: ['qs'] },
  { code: "PBF", label: "Protokoll Netzwerkbesuch fertiggestellt", rollen: ['ab', 'fb'] },
  { code: "VQT-", label: "VN zurück an FB", rollen: ['qs'] },
  { code: "P2KA", label: "kein Antrag auf Phase 2", rollen: ['ab', 'fb'] },
  { code: "P2M", label: "Mahnung Antrag Phase 2", rollen: ['ab', 'fb'] },
  { code: "P2P", label: "Pause beantragt Phase 2", rollen: ['ab', 'fb'] },
  { code: "P2B", label: "Plan Beginn Phase 2", rollen: ['ab', 'fb'] },
  { code: "P2E", label: "Eingang Antrag Phase 2", rollen: ['pa'] },
  { code: "P2+", label: "NW besteht weiter", rollen: ['ab', 'fb'] },
  { code: "P2-", label: "NW gescheitert", rollen: ['ab', 'fb'] },
  { code: "LW", label: "Widerspruch Laufzeitänderung", rollen: [] },
  { code: "LAW", label: "Widerspruch Ablehnung Laufzeit", rollen: [] },
  { code: "LAWA", label: "negativer Widerspruchsbescheid", rollen: [] },
  { code: "LAWZ", label: "positiver Widerspruchsbescheid", rollen: [] },
  { code: "MVW", label: "Widerspruch Mittelverschiebung", rollen: [] },
  { code: "MVAW", label: "Widerspruch Ablehnung Mittelverschiebung", rollen: [] },
  { code: "MVAWA", label: "negativer Widerspruchsbescheid", rollen: [] },
  { code: "MVAWZ", label: "positiver Widerspruchsbescheid", rollen: [] },
  { code: "LBM3", label: "Mahnung Leistungsbestätigung", rollen: [] },
  { code: "VBM3", label: "Mahnung VN-Sach", rollen: [] },
  { code: "VZM3", label: "Mahnung VN-Zahl", rollen: [] },
  { code: "WRH", label: "Widerrufsbescheid geprüft durch PL", rollen: ['qs'] },
  { code: "WRZG+", label: "Freigabe durch BMWK", rollen: ['pa'] },
  { code: "XYB", label: "Brief:", rollen: [] },
  { code: "XYE", label: "E-Mail:", rollen: [] },
  { code: "XYFO", label: "Eingang Foyer", rollen: [] },
  { code: "XYF", label: "Fax:", rollen: [] },
  { code: "XYG", label: "Beratungsgespräch:", rollen: [] },
  { code: "XYW", label: "Wichtig:", rollen: [] },
  { code: "XYPM", label: "Pressemitteilung:", rollen: [] },
  { code: "XPV", label: "Projekt vorgestellt", rollen: [] },
  { code: "XCOV", label: "thematisch COVID19", rollen: [] },
  { code: "XSW", label: "Skizze00x Phase 1/2 oder Wiedereinreicher TB/BB", rollen: ['pa'] },
  { code: "XRN+", label: "regulärer NWP am Projekt beteiligt", rollen: ['fb', 'qs', 'pa'] },
  { code: "XRN-", label: "kein regulärer NWP am Projekt beteiligt", rollen: ['fb', 'qs', 'pa'] },
  { code: "XTE", label: "alle Anträge eingegangen", rollen: ['pa'] },
  { code: "XTEC", label: "alle Anträge in C16 eingegeben", rollen: ['pa'] },
  { code: "XAT", label: "Anzahl der erwarteten Teilvorhaben", rollen: ['pa'] },
  { code: "XAT+", label: "Anzahl der Teilvorhaben (inkl. assoziiert)", rollen: ['pa'] },
  { code: "XANT", label: "Termin Vollständigkeit Verbund", rollen: ['pa'] },
  { code: "XPC+", label: "PreCheck positiv", rollen: ['ab', 'fb', 'qs'] },
  { code: "XPC?", label: "PreCheck Nachforderung", rollen: ['ab', 'fb', 'qs'] },
  { code: "XPC-", label: "PreCheck negativ", rollen: ['ab', 'fb', 'qs'] },
  { code: "XINNO", label: "Innovationsgrad bei GA", rollen: ['qs'] },
  { code: "XALF", label: "alle erforderlichen Nachforderungen sind fertig (AB/FB)", rollen: ['ab', 'fb'] },
  { code: "XARF", label: "alle erforderlichen Rücknahmeempfehlungen sind fertig (AB/FB)", rollen: ['ab', 'fb'] },
  { code: "XQSW", label: "Gutachten QS nach Widerspruch fertig", rollen: ['qs'] },
  { code: "XTG", label: "voraussichtlicher Termin GA (technisch)", rollen: ['fb'] },
  { code: "XFB", label: "Bew. ausgesetzt - max. 2 Bew. in 12 Monaten", rollen: ['qs'] },
  { code: "XHSP", label: "Bew. ausgesetzt - Haushaltssperre", rollen: ['qs'] },
  { code: "XBG", label: "beispielhaftes Gutachten", rollen: ['ab', 'fb', 'qs'] },
  { code: "XSPDOK", label: "Stichprobendokumente an ZG", rollen: [] },
  { code: "XAZBF", label: "alle Zuwendungsbecheide sind erstellt", rollen: ['ab', 'fb'] },
  { code: "XICN", label: "internationaler Call Name", rollen: ['pa'] },
  { code: "XIAAE", label: "Call Ende (internationale Projekte)", rollen: ['pa'] },
  { code: "XIT1", label: "Termin erste Tendenz an AiF", rollen: ['pa'] },
  { code: "XIAIF1", label: "erste Tendenz an AiF gesendet", rollen: ['pa'] },
  { code: "XIT2", label: "Termin finale Entscheidung an AiF", rollen: ['pa'] },
  { code: "XIAIF2", label: "finale Entscheidung an AiF gesendet", rollen: ['pa'] },
  { code: "XIP", label: "Bew. ausgesetzt - Förderentscheidung int. Partner ausstehend", rollen: ['pa'] },
  { code: "XIPA", label: "ausl. Partner wird abgelehnt", rollen: ['ab', 'fb'] },
  { code: "XIPB", label: "ausl. Partner wird bewilligt", rollen: ['ab', 'fb'] },
  { code: "XVU", label: "Eingang unterschriebener Kooperationsvertrag", rollen: [] },
  { code: "XVN", label: "Nachforderung KoopVertrag", rollen: ['ab', 'fb'] },
  { code: "XVL", label: "Nachlieferung KoopVertrag", rollen: [] },
  { code: "XVT", label: "unterschriebener Koop-Vertrag technisch geprüft", rollen: ['fb'] },
  { code: "XVK", label: "unterschriebener Koop-Vertrag kaufmännisch geprüft", rollen: ['ab'] },
  { code: "XVZ", label: "Auflagenerfüllung an ZE Koop-Vertrag", rollen: ['ab'] },
  { code: "XVE", label: "Verbund beendet", rollen: [] },
  { code: "XEFB1", label: "Erfolgsbeispiel angefragt", rollen: ['qs'] },
  { code: "XEFB2", label: "Erfolgsbeispiel bestätigt", rollen: ['qs'] },
  { code: "XEFB3", label: "Erfolgsbeispiel verneint", rollen: ['qs'] },
  { code: "XEFB4", label: "Erfolgsbeispiel in Arbeit", rollen: ['qs'] },
  { code: "XEFB5", label: "Erfolgsbeispiel Freigabe BMWK angefragt", rollen: ['qs'] },
  { code: "XEFB6", label: "Erfolgsbeispiel veröffentlicht (JAHR; deutsch/englisch)", rollen: ['qs'] },
  { code: "XAAE", label: "Eingang des Netzwerkantrages", rollen: ['pa'] },
  { code: "XABB", label: "Bewilligungsdatum des Netzwerks", rollen: ['pa'] },
  { code: "FKTB", label: "Fachkoordinator", rollen: [] },
  { code: "YIRR", label: "FuE / Akronym", rollen: ['pa'] },
  { code: "YIZ", label: "Irrläufer an anderen PT AiF/EN", rollen: ['pa'] },
  { code: "PC+", label: "pre-check positiv", rollen: ['ab', 'fb', 'qs'] },
  { code: "PC?", label: "pre-check unvollständig", rollen: ['ab', 'fb', 'qs'] },
  { code: "PC-", label: "pre-check negativ", rollen: ['ab', 'fb', 'qs'] },
  { code: "PCAN", label: "pre-check Nachforderungen an ASt", rollen: ['ab', 'fb', 'qs'] },
  { code: "PCQ", label: "pre-check NF Qualitätssicherung", rollen: ['qs'] },
  { code: "PCAL", label: "pre-check Nachlieferungen", rollen: [] },
  { code: "ÄG", label: "Unterlagen zur Änderung der Zuweisung ans BMWK", rollen: ['pa'] },
  { code: "LG", label: "Unterlagen zur Änderung der Zuweisung ans BMWK", rollen: ['pa'] },
  { code: "MVG", label: "Unterlagen zur Änderung der Zuweisung ans BMWK", rollen: ['pa'] },
  { code: "ZABB", label: "Zuweisung wurde bewilligt - bitte in PROFI anlegen", rollen: ['qs'] },
  { code: "ZDV", label: "Zuweisung in profi angelegt", rollen: ['qs'] },
  { code: "ZN", label: "Eingang Zwischennachweis", rollen: [] },
  { code: "ZNN", label: "Nachforderung/Rückfragen zum ZN", rollen: ['ab', 'fb'] },
  { code: "ZNL", label: "Nachlieferung zum ZN", rollen: [] },
  { code: "ZNKS", label: "Zwischennachweis kaufmännisch geprüft", rollen: ['ab'] },
  { code: "ZNTS", label: "Zwischennachweis technisch geprüft", rollen: ['fb'] },
  { code: "ZNGZ", label: "Zwischennachweis in profi gebucht", rollen: ['ab'] },
  { code: "ZQS", label: "QS Änderung ist erfolgt - Ä/L/MV", rollen: ['qs'] },
  { code: "PROFI", label: "Kapitel - Objektkonto - HKR-Nr.", rollen: ['ab', 'fb'] },
  { code: "ZBFI", label: "Weitergabe Bearbeitung Zwischenbericht", rollen: ['ab', 'fb'] },
  { code: "IAKZ", label: "Aktenzeichen vom Gericht", rollen: ['jur'] },
  { code: "IP", label: "Kenntnisnahme von Insolvenz des Partners", rollen: ['ab', 'fb', 'qs', 'jur'] },
  { code: "IFAX", label: "keine FA notwendig - ohne Auszahlung", rollen: ['ab'] },
  { code: "VPSP1", label: "Stichprobe - Stufe 1", rollen: ['ab', 'fb'] },
  { code: "VPB1", label: "Belegliste angefordert", rollen: ['ab', 'fb'] },
  { code: "VPB1A", label: "Eingang Belegliste", rollen: ['ab', 'fb'] },
  { code: "VPSP2", label: "Stichprobe - Stufe 2", rollen: ['ab', 'fb'] },
  { code: "VPB2", label: "Belege/RE angefordert", rollen: ['ab', 'fb'] },
  { code: "VPB2A", label: "Eingang Belege/RE", rollen: [] },
  { code: "VNFI", label: "Weitergabe Bearbeitung Verwendungsnachweis", rollen: ['ab', 'fb'] },
  { code: "VRM1", label: "Erinnerung Rückzahlung", rollen: [] },
  { code: "WZBE", label: "Eingang Widerspruch Zuw.Bescheid", rollen: [] },
  { code: "WZBR", label: "Widerspruch Zuw.Bescheid zurückgezogen", rollen: [] },
  { code: "WZBA", label: "Widerspruch ZUB abgelehnt", rollen: ['pa'] },
  { code: "WZBS", label: "Widerspruch ZUB stattgegeben", rollen: ['pa'] },
  { code: "WZBTS", label: "Widerspruch ZUB teilweise stattgegeben", rollen: ['pa'] },
  { code: "WZBQ", label: "Widerspruchsbescheid ZUB Qualitätssicherung", rollen: ['qs'] },
  { code: "WZBZ", label: "Widerspruchsbescheid an ZE", rollen: ['pa'] },
  { code: "WZBD", label: "Widerspruchsbescheid rechtskräftig", rollen: ['pa'] },
  { code: "LWR", label: "Widerspruch Laufzeit zurückgezogen", rollen: [] },
  { code: "MVWR", label: "Widerspruch MV zurückgezogen", rollen: [] },
];

/** Dateiname der eingelesenen Zuarbeit — steht im Cockpit als Herkunftsnachweis. */
export const ZUARBEIT_QUELLE = "kuerzel-zuarbeit-20260724.csv";
