import type { Vorgang } from '@/core/types/vorgang';

const a = (id: string, title: string, status: Vorgang['status'], priority: Vorgang['priority'], assignee: string, tags: string[], notes: string, deadline?: string, created = '2026-01-15T08:00:00Z'): Vorgang => ({
  id, type: 'bauantrag', title, status, priority, assignee, created, modified: created, deadline, tags, notes,
});

export const bauantraegeData: Vorgang[] = [
  a('BA-2026-001', 'Neubau Einfamilienhaus, Ahornweg 15', 'genehmigt', 'normal', 'Schmidt', ['Neubau', 'EFH', 'Wohngebiet'], 'Alle Unterlagen vollständig. Genehmigung erteilt am 15.02.2026. Auflagen zum Regenwassermanagement beachten.'),
  a('BA-2026-002', 'Neubau Mehrfamilienhaus, Lindenstraße 42', 'in_pruefung', 'hoch', 'Müller', ['Neubau', 'MFH', 'Verdichtung'], 'Statik-Gutachten liegt vor. Brandschutzkonzept in Prüfung bei Feuerwehr. 12 Wohneinheiten auf 4 Geschossen.', '2026-04-30', '2026-01-20T08:00:00Z'),
  a('BA-2026-003', 'Anbau Wintergarten, Buchenring 7', 'genehmigt', 'niedrig', 'Weber', ['Anbau', 'Wintergarten'], 'Grenzabstand eingehalten. Nachbar hat zugestimmt. Unbedenklich.', undefined, '2026-01-22T08:00:00Z'),
  a('BA-2026-004', 'Dachgeschossausbau, Kastanienallee 23', 'nachforderung', 'normal', 'Schmidt', ['Ausbau', 'Dachgeschoss', 'Statik'], 'Tragwerksnachweis fehlt. Nachforderung an Bauherrn versendet am 10.03.2026. Frist: 10.04.2026.', '2026-04-10', '2026-02-01T08:00:00Z'),
  a('BA-2026-005', 'Nutzungsänderung Scheune zu Wohnraum, Dorfstraße 8', 'in_bearbeitung', 'hoch', 'Fischer', ['Nutzungsänderung', 'Denkmal', 'Umbau'], 'Denkmalschutzrechtliche Stellungnahme angefordert. Bestandsgebäude von 1890. Heizkonzept offen.', '2026-05-15', '2026-02-05T08:00:00Z'),
  a('BA-2026-006', 'Abbruch Altbestand + Neubau, Industrieweg 3', 'in_pruefung', 'dringend', 'Koch', ['Abbruch', 'Neubau', 'Gewerbe', 'Altlasten'], 'Altlastengutachten zeigt Bodenbelastung mit PAK. Sanierungskonzept erforderlich vor Baubeginn.', '2026-03-31', '2026-02-10T08:00:00Z'),
  a('BA-2026-007', 'Carport mit Gründach, Rosenweg 19', 'genehmigt', 'niedrig', 'Weber', ['Carport', 'Gründach'], 'Verfahrensfrei nach §63. Informationsschreiben an Bauherrn versandt.'),
  a('BA-2026-008', 'Gewerbehalle mit Bürotrakt, Gewerbepark Süd 12', 'in_bearbeitung', 'hoch', 'Müller', ['Gewerbe', 'Neubau', 'Erschließung'], 'Erschließungsvertrag mit Gemeinde in Verhandlung. B-Plan-Änderung erforderlich für GRZ-Überschreitung.', '2026-06-30', '2026-02-15T08:00:00Z'),
  a('BA-2026-009', 'Solardachanlage auf Bestandsgebäude, Marktplatz 5', 'genehmigt', 'normal', 'Fischer', ['Solar', 'Denkmal', 'Energie'], 'Denkmalschutzrechtliche Genehmigung erteilt unter Auflagen. Nur dachintegrierte Module zulässig.'),
  a('BA-2026-010', 'Tiefgarage unter Wohnanlage, Parkstraße 30', 'in_pruefung', 'dringend', 'Koch', ['Tiefgarage', 'Statik', 'Grundwasser'], 'Hydrogeologisches Gutachten zeigt hohen Grundwasserspiegel. Weiße Wanne erforderlich. Kosten steigen erheblich.', '2026-04-15', '2026-02-20T08:00:00Z'),
  a('BA-2026-011', 'Aufstockung Bestandsgebäude, Schulstraße 14', 'nachforderung', 'hoch', 'Schmidt', ['Aufstockung', 'Statik', 'Wohnraum'], 'Bestandsstatik tragfähig laut Gutachten. Schallschutznachweis für die neue Nutzungseinheit fehlt noch.', '2026-04-20', '2026-02-25T08:00:00Z'),
  a('BA-2026-012', 'Kindertagesstätte Neubau, Am Stadtpark 1', 'in_bearbeitung', 'dringend', 'Müller', ['Kita', 'Neubau', 'Sozial'], 'Förderantrag beim Land gestellt. Raumprogramm mit Jugendamt abgestimmt. Barrierefreiheit nach DIN 18040 sicherstellen.', '2026-05-31', '2026-03-01T08:00:00Z'),
  a('BA-2026-013', 'Umbau Ladengeschäft zu Gastronomie, Hauptstraße 67', 'in_pruefung', 'normal', 'Weber', ['Umbau', 'Gastronomie', 'Nutzungsänderung'], 'Lüftungskonzept vorgelegt. Stellungnahme Gesundheitsamt steht aus. Lärmschutzgutachten wegen Außengastronomie erforderlich.', '2026-05-15'),
  a('BA-2026-014', 'Wohnhaus mit Einliegerwohnung, Feldweg 4', 'genehmigt', 'niedrig', 'Fischer', ['Neubau', 'EFH', 'Einlieger'], 'Standard-Wohngebiet. Alle Nachweise vollständig. KfW-55-Standard.'),
  a('BA-2026-015', 'Rückbau und Entsiegelung, Bahnhofstraße 22', 'in_bearbeitung', 'normal', 'Koch', ['Rückbau', 'Entsiegelung', 'Ökologie'], 'Entsiegelungskonzept positiv bewertet. Ausgleichsfläche im Bebauungsplan festgesetzt.'),
  a('BA-2026-016', 'Mehrfamilienhaus mit Quartiersgarage, Neue Mitte 8', 'in_pruefung', 'hoch', 'Schmidt', ['MFH', 'Quartiersgarage', 'Mobilität'], 'Mobilitätskonzept mit reduziertem Stellplatzschlüssel. Carsharing-Stellplätze vorgesehen.', '2026-06-15'),
  a('BA-2026-017', 'Tiny House Siedlung, Obstgartenweg 3', 'nachforderung', 'normal', 'Müller', ['Tiny House', 'Sondergebiet', 'Innovation'], 'B-Plan sieht keine Tiny Houses vor. Befreiungsantrag gestellt. Erschließung über Sammelleitung geplant.', '2026-04-30'),
  a('BA-2026-018', 'Seniorenwohnanlage mit Tagespflege, Kirchplatz 11', 'in_bearbeitung', 'hoch', 'Weber', ['Senioren', 'Pflege', 'Barrierefreiheit'], 'Abstimmung mit Sozialbehörde läuft. Förderantrag beim Pflegefonds eingereicht. 24 Wohneinheiten plus Gemeinschaftsräume.', '2026-07-31'),
  a('BA-2026-019', 'Photovoltaik-Freiflächenanlage, Flur 7 Gemarkung Ost', 'in_pruefung', 'normal', 'Fischer', ['PV', 'Freifläche', 'Energie', 'Landwirtschaft'], 'Naturschutzrechtliche Prüfung wegen Feldlerchenvorkommen. Agri-PV Konzept als Alternative geprüft.'),
  a('BA-2026-020', 'Hochwasserschutzmauer, Uferpromenade', 'in_bearbeitung', 'dringend', 'Koch', ['Hochwasser', 'Infrastruktur', 'Schutz'], 'Hydraulisches Gutachten zeigt HQ100-Risiko. Eilbedürfnis wegen bevorstehender Schneeschmelze. Fördermittel bewilligt.', '2026-03-15'),
  a('BA-2026-021', 'Sanierung Fachwerkhaus, Altstadt 9', 'nachforderung', 'normal', 'Schmidt', ['Sanierung', 'Fachwerk', 'Denkmal'], 'Befund Holzschutzgutachten steht aus. Hausschwammbefall vermutet. Denkmalschutz fordert Originalsubstanz-Erhalt.', '2026-05-01'),
  a('BA-2026-022', 'Neubau Arztpraxis mit Labor, Gesundheitszentrum 2', 'in_pruefung', 'hoch', 'Müller', ['Neubau', 'Gewerbe', 'Medizin', 'Labor'], 'Hygienekonzept nach RKI-Richtlinien erforderlich. Laborabwasser-Vorbehandlung klären mit Umweltamt.', '2026-05-31'),
  a('BA-2026-023', 'Erweiterung Grundschule um 4 Klassenräume, Schulberg 5', 'in_bearbeitung', 'dringend', 'Weber', ['Erweiterung', 'Schule', 'Sozial'], 'Interimscontainer bereits aufgestellt. Permanentbau soll bis Sommer 2027 stehen. Lärmschutz während Bauphase beachten.', '2026-08-31'),
  a('BA-2026-024', 'Bau Radschnellweg-Brücke, Flussquerung Km 2.4', 'in_pruefung', 'hoch', 'Koch', ['Brücke', 'Infrastruktur', 'Mobilität', 'Radverkehr'], 'Statik für Leichtbaubrücke (Stahl-Holz-Hybrid) geprüft. Umweltverträglichkeitsprüfung abgeschlossen. Eingriffs-Ausgleich über Uferrenaturierung.', '2026-06-30'),
];
